name: Check label

on:
  # Allows you to run this workflow manually from the Actions tab
  pull_request:
    types: [labeled]
  
jobs:
  check-label:
    runs-on: ubuntu-latest

    steps:
      - id: step1
        name: Run a one-line script
        if: contains(github.event.pull_request.labels.*.name, 'automerge')
        run: echo 'Unregister Jira webhook here!'
  next-job:
    runs-on: ubuntu-latest
    needs: [check-label]
    if: (contains(github.event.pull_request.labels.*.name, 'automerge') == false)
    steps:
      - run: echo 'Run check issue'
